alias cat=bat
alias diff=batdiff
alias dig=dog
alias du=dust
alias find=fd
alias grep=batgrep
alias l='lsd -F'
alias la='lsd -A'
alias ll='lsd -l'
alias ls=lsd
alias man=batman
alias ping=gping
alias sed=sd
alias top=btm
